# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3' 


common: &common
  adapter: postgresql
  username: dotsearchfile
  password: calculus

development:
  <<: *common
  database: dotsearchfile_dev

test:
  <<: *common
  database: dotsearchfile_test

production:
  <<: *common
  database: dotsearchfile