require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ListSubscriptionsController do

  # This should return the minimal set of attributes required to create a valid
  # ListSubscription. As you add validations to ListSubscription, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all list_subscriptions as @list_subscriptions" do
      list_subscription = ListSubscription.create! valid_attributes
      get :index
      assigns(:list_subscriptions).should eq([list_subscription])
    end
  end

  describe "GET show" do
    it "assigns the requested list_subscription as @list_subscription" do
      list_subscription = ListSubscription.create! valid_attributes
      get :show, :id => list_subscription.id.to_s
      assigns(:list_subscription).should eq(list_subscription)
    end
  end

  describe "GET new" do
    it "assigns a new list_subscription as @list_subscription" do
      get :new
      assigns(:list_subscription).should be_a_new(ListSubscription)
    end
  end

  describe "GET edit" do
    it "assigns the requested list_subscription as @list_subscription" do
      list_subscription = ListSubscription.create! valid_attributes
      get :edit, :id => list_subscription.id.to_s
      assigns(:list_subscription).should eq(list_subscription)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ListSubscription" do
        expect {
          post :create, :list_subscription => valid_attributes
        }.to change(ListSubscription, :count).by(1)
      end

      it "assigns a newly created list_subscription as @list_subscription" do
        post :create, :list_subscription => valid_attributes
        assigns(:list_subscription).should be_a(ListSubscription)
        assigns(:list_subscription).should be_persisted
      end

      it "redirects to the created list_subscription" do
        post :create, :list_subscription => valid_attributes
        response.should redirect_to(ListSubscription.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved list_subscription as @list_subscription" do
        # Trigger the behavior that occurs when invalid params are submitted
        ListSubscription.any_instance.stub(:save).and_return(false)
        post :create, :list_subscription => {}
        assigns(:list_subscription).should be_a_new(ListSubscription)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ListSubscription.any_instance.stub(:save).and_return(false)
        post :create, :list_subscription => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested list_subscription" do
        list_subscription = ListSubscription.create! valid_attributes
        # Assuming there are no other list_subscriptions in the database, this
        # specifies that the ListSubscription created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ListSubscription.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => list_subscription.id, :list_subscription => {'these' => 'params'}
      end

      it "assigns the requested list_subscription as @list_subscription" do
        list_subscription = ListSubscription.create! valid_attributes
        put :update, :id => list_subscription.id, :list_subscription => valid_attributes
        assigns(:list_subscription).should eq(list_subscription)
      end

      it "redirects to the list_subscription" do
        list_subscription = ListSubscription.create! valid_attributes
        put :update, :id => list_subscription.id, :list_subscription => valid_attributes
        response.should redirect_to(list_subscription)
      end
    end

    describe "with invalid params" do
      it "assigns the list_subscription as @list_subscription" do
        list_subscription = ListSubscription.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ListSubscription.any_instance.stub(:save).and_return(false)
        put :update, :id => list_subscription.id.to_s, :list_subscription => {}
        assigns(:list_subscription).should eq(list_subscription)
      end

      it "re-renders the 'edit' template" do
        list_subscription = ListSubscription.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ListSubscription.any_instance.stub(:save).and_return(false)
        put :update, :id => list_subscription.id.to_s, :list_subscription => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested list_subscription" do
      list_subscription = ListSubscription.create! valid_attributes
      expect {
        delete :destroy, :id => list_subscription.id.to_s
      }.to change(ListSubscription, :count).by(-1)
    end

    it "redirects to the list_subscriptions list" do
      list_subscription = ListSubscription.create! valid_attributes
      delete :destroy, :id => list_subscription.id.to_s
      response.should redirect_to(list_subscriptions_url)
    end
  end

end
