require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ListOwnershipsController do

  # This should return the minimal set of attributes required to create a valid
  # ListOwnership. As you add validations to ListOwnership, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all list_ownerships as @list_ownerships" do
      list_ownership = ListOwnership.create! valid_attributes
      get :index
      assigns(:list_ownerships).should eq([list_ownership])
    end
  end

  describe "GET show" do
    it "assigns the requested list_ownership as @list_ownership" do
      list_ownership = ListOwnership.create! valid_attributes
      get :show, :id => list_ownership.id.to_s
      assigns(:list_ownership).should eq(list_ownership)
    end
  end

  describe "GET new" do
    it "assigns a new list_ownership as @list_ownership" do
      get :new
      assigns(:list_ownership).should be_a_new(ListOwnership)
    end
  end

  describe "GET edit" do
    it "assigns the requested list_ownership as @list_ownership" do
      list_ownership = ListOwnership.create! valid_attributes
      get :edit, :id => list_ownership.id.to_s
      assigns(:list_ownership).should eq(list_ownership)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ListOwnership" do
        expect {
          post :create, :list_ownership => valid_attributes
        }.to change(ListOwnership, :count).by(1)
      end

      it "assigns a newly created list_ownership as @list_ownership" do
        post :create, :list_ownership => valid_attributes
        assigns(:list_ownership).should be_a(ListOwnership)
        assigns(:list_ownership).should be_persisted
      end

      it "redirects to the created list_ownership" do
        post :create, :list_ownership => valid_attributes
        response.should redirect_to(ListOwnership.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved list_ownership as @list_ownership" do
        # Trigger the behavior that occurs when invalid params are submitted
        ListOwnership.any_instance.stub(:save).and_return(false)
        post :create, :list_ownership => {}
        assigns(:list_ownership).should be_a_new(ListOwnership)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ListOwnership.any_instance.stub(:save).and_return(false)
        post :create, :list_ownership => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested list_ownership" do
        list_ownership = ListOwnership.create! valid_attributes
        # Assuming there are no other list_ownerships in the database, this
        # specifies that the ListOwnership created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ListOwnership.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => list_ownership.id, :list_ownership => {'these' => 'params'}
      end

      it "assigns the requested list_ownership as @list_ownership" do
        list_ownership = ListOwnership.create! valid_attributes
        put :update, :id => list_ownership.id, :list_ownership => valid_attributes
        assigns(:list_ownership).should eq(list_ownership)
      end

      it "redirects to the list_ownership" do
        list_ownership = ListOwnership.create! valid_attributes
        put :update, :id => list_ownership.id, :list_ownership => valid_attributes
        response.should redirect_to(list_ownership)
      end
    end

    describe "with invalid params" do
      it "assigns the list_ownership as @list_ownership" do
        list_ownership = ListOwnership.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ListOwnership.any_instance.stub(:save).and_return(false)
        put :update, :id => list_ownership.id.to_s, :list_ownership => {}
        assigns(:list_ownership).should eq(list_ownership)
      end

      it "re-renders the 'edit' template" do
        list_ownership = ListOwnership.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ListOwnership.any_instance.stub(:save).and_return(false)
        put :update, :id => list_ownership.id.to_s, :list_ownership => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested list_ownership" do
      list_ownership = ListOwnership.create! valid_attributes
      expect {
        delete :destroy, :id => list_ownership.id.to_s
      }.to change(ListOwnership, :count).by(-1)
    end

    it "redirects to the list_ownerships list" do
      list_ownership = ListOwnership.create! valid_attributes
      delete :destroy, :id => list_ownership.id.to_s
      response.should redirect_to(list_ownerships_url)
    end
  end

end
