require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SearchListsController do

  # This should return the minimal set of attributes required to create a valid
  # SearchList. As you add validations to SearchList, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all search_lists as @search_lists" do
      search_list = SearchList.create! valid_attributes
      get :index
      assigns(:search_lists).should eq([search_list])
    end
  end

  describe "GET show" do
    it "assigns the requested search_list as @search_list" do
      search_list = SearchList.create! valid_attributes
      get :show, :id => search_list.id.to_s
      assigns(:search_list).should eq(search_list)
    end
  end

  describe "GET new" do
    it "assigns a new search_list as @search_list" do
      get :new
      assigns(:search_list).should be_a_new(SearchList)
    end
  end

  describe "GET edit" do
    it "assigns the requested search_list as @search_list" do
      search_list = SearchList.create! valid_attributes
      get :edit, :id => search_list.id.to_s
      assigns(:search_list).should eq(search_list)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new SearchList" do
        expect {
          post :create, :search_list => valid_attributes
        }.to change(SearchList, :count).by(1)
      end

      it "assigns a newly created search_list as @search_list" do
        post :create, :search_list => valid_attributes
        assigns(:search_list).should be_a(SearchList)
        assigns(:search_list).should be_persisted
      end

      it "redirects to the created search_list" do
        post :create, :search_list => valid_attributes
        response.should redirect_to(SearchList.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved search_list as @search_list" do
        # Trigger the behavior that occurs when invalid params are submitted
        SearchList.any_instance.stub(:save).and_return(false)
        post :create, :search_list => {}
        assigns(:search_list).should be_a_new(SearchList)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        SearchList.any_instance.stub(:save).and_return(false)
        post :create, :search_list => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested search_list" do
        search_list = SearchList.create! valid_attributes
        # Assuming there are no other search_lists in the database, this
        # specifies that the SearchList created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        SearchList.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => search_list.id, :search_list => {'these' => 'params'}
      end

      it "assigns the requested search_list as @search_list" do
        search_list = SearchList.create! valid_attributes
        put :update, :id => search_list.id, :search_list => valid_attributes
        assigns(:search_list).should eq(search_list)
      end

      it "redirects to the search_list" do
        search_list = SearchList.create! valid_attributes
        put :update, :id => search_list.id, :search_list => valid_attributes
        response.should redirect_to(search_list)
      end
    end

    describe "with invalid params" do
      it "assigns the search_list as @search_list" do
        search_list = SearchList.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SearchList.any_instance.stub(:save).and_return(false)
        put :update, :id => search_list.id.to_s, :search_list => {}
        assigns(:search_list).should eq(search_list)
      end

      it "re-renders the 'edit' template" do
        search_list = SearchList.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SearchList.any_instance.stub(:save).and_return(false)
        put :update, :id => search_list.id.to_s, :search_list => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested search_list" do
      search_list = SearchList.create! valid_attributes
      expect {
        delete :destroy, :id => search_list.id.to_s
      }.to change(SearchList, :count).by(-1)
    end

    it "redirects to the search_lists list" do
      search_list = SearchList.create! valid_attributes
      delete :destroy, :id => search_list.id.to_s
      response.should redirect_to(search_lists_url)
    end
  end

end
